version: 2.1

defaults: &defaults
  docker:
    - image: python:3.6-buster

jobs:

  lint_markdown:
    <<: *defaults
    docker:
      - image: node:11-slim
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  check_rst:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install sphinx
          command: |
            pip install sphinx sphinx-rtd-theme rstcheck pygments
      - run:
          name: Lint rst
          command: |
            rstcheck --report warning *.rst

  make_html:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Apptainer submodule init
          command: |
            git submodule update --init --recursive
      - run:
          name: Install sphinx
          command: |
            pip install sphinx sphinx-rtd-theme restructuredtext_lint pygments
      - run:
          name: make html
          command: |
            make html
      - store_artifacts:
          path: _build/html
          destination: html

  make_pdf_epub:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install sphinx
          command: |
            pip install sphinx sphinx-rtd-theme restructuredtext_lint pygments
      - run:
          name: Install TeXlive
          command: |
            apt-get update
            apt-get install -f -y texlive-latex-extra latexmk
      - run:
          name: make pdf
          command: |
            make latexpdf
      - store_artifacts:
          path: _build/latex
          destination: pdf
      - run:
          name: make epub
          command: |
            make epub
      - store_artifacts:
          path: _build/epub
          destination: epub

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_markdown
      - check_rst
      - make_html:
          requires:
            - check_rst
      - make_pdf_epub:
          requires:
            - check_rst

